set_property IOSTANDARD LVCMOS33 [get_ports {O_blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_blue[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {O_green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_green[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {O_red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_red[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports I_clk_100M]
set_property IOSTANDARD LVCMOS33 [get_ports I_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {I_new[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {I_new[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports O_hs]
set_property IOSTANDARD LVCMOS33 [get_ports O_vs]
set_property IOSTANDARD LVCMOS33 [get_ports O_gameover]

set_property PACKAGE_PIN D8 [get_ports {O_blue[3]}]
set_property PACKAGE_PIN D7 [get_ports {O_blue[2]}]
set_property PACKAGE_PIN C7 [get_ports {O_blue[1]}]
set_property PACKAGE_PIN B7 [get_ports {O_blue[0]}]

set_property PACKAGE_PIN A6 [get_ports {O_green[3]}]
set_property PACKAGE_PIN B6 [get_ports {O_green[2]}]
set_property PACKAGE_PIN A5 [get_ports {O_green[1]}]
set_property PACKAGE_PIN C6 [get_ports {O_green[0]}]

set_property PACKAGE_PIN A4 [get_ports {O_red[3]}]
set_property PACKAGE_PIN C5 [get_ports {O_red[2]}]
set_property PACKAGE_PIN B4 [get_ports {O_red[1]}]
set_property PACKAGE_PIN A3 [get_ports {O_red[0]}]

set_property PACKAGE_PIN E3 [get_ports I_clk_100M]
set_property PACKAGE_PIN J15 [get_ports I_rst_n]
set_property PACKAGE_PIN H6 [get_ports {I_new[0]}]
set_property PACKAGE_PIN T13 [get_ports {I_new[1]}]


set_property PACKAGE_PIN B11 [get_ports O_hs]
set_property PACKAGE_PIN B12 [get_ports O_vs]
set_property PACKAGE_PIN K15 [get_ports O_gameover]

set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]
set_property PACKAGE_PIN F4 [get_ports ps2_clk]
set_property PACKAGE_PIN B2 [get_ports ps2_data]

set_property IOSTANDARD LVCMOS33 [get_ports I_down]
set_property IOSTANDARD LVCMOS33 [get_ports I_left]
set_property IOSTANDARD LVCMOS33 [get_ports I_right]
set_property IOSTANDARD LVCMOS33 [get_ports I_up]
set_property IOSTANDARD LVCMOS33 [get_ports I_reset]
set_property PACKAGE_PIN M18 [get_ports I_up]
set_property PACKAGE_PIN M17 [get_ports I_right]
set_property PACKAGE_PIN P18 [get_ports I_down]
set_property PACKAGE_PIN P17 [get_ports I_left]
set_property PACKAGE_PIN N17 [get_ports I_reset]

set_property IOSTANDARD LVCMOS33 [get_ports {O_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_data[4]}]
set_property PACKAGE_PIN L18 [get_ports {O_data[6]}]
set_property PACKAGE_PIN T11 [get_ports {O_data[5]}]
set_property PACKAGE_PIN P15 [get_ports {O_data[4]}]
set_property PACKAGE_PIN K13 [get_ports {O_data[3]}]
set_property PACKAGE_PIN K16 [get_ports {O_data[2]}]
set_property PACKAGE_PIN R10 [get_ports {O_data[1]}]
set_property PACKAGE_PIN T10 [get_ports {O_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {O_shift[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_shift[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_shift[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_shift[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_shift[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_shift[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_shift[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {O_shift[0]}]
set_property PACKAGE_PIN U13 [get_ports {O_shift[7]}]
set_property PACKAGE_PIN K2 [get_ports {O_shift[6]}]
set_property PACKAGE_PIN T14 [get_ports {O_shift[5]}]
set_property PACKAGE_PIN P14 [get_ports {O_shift[4]}]
set_property PACKAGE_PIN J14 [get_ports {O_shift[3]}]
set_property PACKAGE_PIN T9 [get_ports {O_shift[2]}]
set_property PACKAGE_PIN J18 [get_ports {O_shift[1]}]
set_property PACKAGE_PIN J17 [get_ports {O_shift[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports DREQ]
set_property PACKAGE_PIN J2 [get_ports DREQ]
set_property IOSTANDARD LVCMOS33 [get_ports PLAY]
set_property IOSTANDARD LVCMOS33 [get_ports SCK]
set_property IOSTANDARD LVCMOS33 [get_ports SI]
set_property IOSTANDARD LVCMOS33 [get_ports XCS]
set_property IOSTANDARD LVCMOS33 [get_ports XDCS]
set_property IOSTANDARD LVCMOS33 [get_ports XRESET]
set_property PACKAGE_PIN U18 [get_ports PLAY]
set_property PACKAGE_PIN J3 [get_ports SCK]
set_property PACKAGE_PIN J4 [get_ports SI]
set_property PACKAGE_PIN E7 [get_ports XCS]
set_property PACKAGE_PIN K1 [get_ports XDCS]
set_property PACKAGE_PIN F6 [get_ports XRESET]